# GitHub Pages configuration
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Site settings
title: Product Management API Documentation
description: RESTful API for business product management with rate limiting
show_downloads: true
google_analytics: